### ISSUE TITLE
value::operator= does not allow for navigation

### ISSUE THREAD

**Issue by GabrieleGiuseppini** [kazuho/picojson#65]
The current implementation of value::operator= first destroys the current value and _then_ assigns the new value.

This breaks cases in which you want to descend iteratively down an object hiearchy, as in the following example:

    for (auto k : paths) // paths is an iterator of keys
    {
        if (branchV.is<picojson::null>()
            || !branchV.is<picojson::object>())
        {
            throw JSONFieldConversionException("JSON value is null or not an object");
        }

        const picojson::value::object & obj = branchV.get<picojson::object>();
        const auto & it = obj.find(k);
        if (it == obj.end())
        {
                throw JSONFieldConversionException("Cannot find element \"" + k + "\" in JSON object");
        }

        branchV = it->second; // this breaks
    }
The last statement breaks because the assignment first destroys the current value, which ends up invalidating the iterator.

**Comment by kazuho** [comment]
Thank you for reporting the issue with details.  It is evident that we should fix the implementation.

**Comment by GabrieleGiuseppini** [comment]
Thanks for replying, Kazuho.

I think the fix is easy; the affected code is:
    inline value& value::operator=(const value& x) {
        if (this != &x) {
          this->~value();
          new (this) value(x);
        }
        return *this;
      }

The fix would be to save the old value to a temporary variable, do the assignment, and only then delete the temporary variable.

**Comment by kazuho** [comment]
@GabrieleGiuseppini Thank you for the suggestion.

I have created the PR above to fix the issue in an efficient exception-safe way.  Would you mind checking if it fixes your problem?

**Comment by GabrieleGiuseppini** [comment]
I've tested it and it works perfectly!!! Thanks Kazuho!

When will it be released?

**Comment by kazuho** [comment]
Thank you for checking.  I've just merged the PR to master.  Please wait for a day or so if you want me to tag a release.
